from ansible_playbook import Ansible_playbook
from shell import Shell
from kill_switch import Kill_switch
from say import Say
from script import Script
from sleep import Sleep
from systemdate import Systemdate
from gmail_checker import Gmail_checker
from push_message import Push_message
from openweathermap import Openweathermap
from tasker_autoremote import Tasker_autoremote
from wake_on_lan import Wake_on_lan
