from ansible_tasks import Ansible_tasks
from command import Command
from kill_switch import Kill_switch
from say import Say
from script import Script
from sleep import Sleep
from systemdate import Systemdate
from gmail_checker import Gmail_checker
from push_message import Push_message
from tasker_autoremote import Tasker_autoremote
from wake_on_lan import Wake_on_lan
